name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.29.0
        with:
          php-version: '8.1'
          tools: composer:v2, phpunit:9.5
#     
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
        
      - name: Run PHPUnit
        run: vendor/bin/phpunit --testsuite unit
